### ISSUE TITLE
Failed to start: Cannot read properties of undefined (reading 'length')

### ISSUE THREAD

**Issue by VibroAxe** [KvotheBloodless/signalk-pushover-notification-relay#1]
In signalk-server 1.44.0 I get the below error from the plugin on startup.

![image](https://user-images.githubusercontent.com/1069212/183411886-f519ccd8-9b4c-4d75-8320-44cdc99ffd07.png)

And the following in the server log

```
Aug 08 12:48:08 TypeError: Cannot read properties of undefined (reading 'length') 
at Object.plugin.start (/home/pi/.signalk/node_modules/signalk-pushover-notification-relay/index.js:24:29)
at doPluginStart (/usr/lib/node_modules/signalk-server/lib/interfaces/plugins.js:271:20)
at doRegisterPlugin (/usr/lib/node_modules/signalk-server/lib/interfaces/plugins.js:394:13)
at registerPlugin (/usr/lib/node_modules/signalk-server/lib/interfaces/plugins.js:225:13)
at /usr/lib/node_modules/signalk-server/lib/interfaces/plugins.js:176:13
at Array.forEach (<anonymous>)
at startPlugins (/usr/lib/node_modules/signalk-server/lib/interfaces/plugins.js:175:70) at Object.start (/usr/lib/node_modules/signalk-server/lib/interfaces/plugins.js:40:13)
at /usr/lib/node_modules/signalk-server/lib/index.js:438:70
at /usr/lib/node_modules/signalk-server/node_modules/lodash/lodash.js:4967:15
at Function.forIn (/usr/lib/node_modules/signalk-server/node_modules/lodash/lodash.js:13018:11)
at startInterfaces (/usr/lib/node_modules/signalk-server/lib/index.js:428:22)
at /usr/lib/node_modules/signalk-server/lib/index.js:275:17
at createServer (/usr/lib/node_modules/signalk-server/lib/index.js:395:5)
at /usr/lib/node_modules/signalk-server/lib/index.js:264:13
at new Promise (<anonymous>)```

**Comment by VibroAxe** [comment]
Editing the config section to try to add a blank notification selector and then removing it seems to have resolved this. Definitely something weird going on. Suspect it needs a null check here> https://github.com/KvotheBloodless/signalk-pushover-notification-relay/blob/d5f628e93b361bf3892049b2194f089171f289c0/index.js#L24

**Comment by lamasseriadipolverara** [comment]
I had the same issue. but can't figured out how you solve it. Try to modify notifigation.lenght has you suggest but didn't work for me. 
Have you permanently fix it?
In the meanwhile i used node-red but prefere have it in signalk... any suggestion?

**Comment by PiotrSol** [comment]
The same here: 
Failed to start: Cannot read properties of undefined (reading 'length')

**Comment by eburi** [comment]
This PR would fix it: https://github.com/KvotheBloodless/signalk-pushover-notification-relay/pull/2

Also fixes an error I get when notifications are sent to the plugin in `handle_notification_delta`.

I guess this is related to changes in the signalk-server

**Comment by PiotrSol** [comment]
Im running SignalK on Victron OS so the SK version is 2.14.4 (I hope they will update to 2.15.x this week)

**Comment by PiotrSol** [comment]
SignalK now on 2.17.2, the same error
